export default [
  { id: 1, name: "Buzz", img: "public/cards-img/Buzz.jpg", inMemory: false },
  {
    id: 2,
    name: "Darth-Vader",
    img: "public/cards-img/Darth-Vader.jpg",
    inMemory: false,
  },
  {
    id: 3,
    name: "Donkey",
    img: "public/cards-img/Donkey.jpg",
    inMemory: false,
  },
  {
    id: 4,
    name: "Gollum",
    img: "public/cards-img/Gollum.jpg",
    inMemory: false,
  },
  {
    id: 5,
    name: "Harry-Potter",
    img: "public/cards-img/Harry-Potter.jpg",
    inMemory: false,
  },
  {
    id: 6,
    name: "Hermione",
    img: "public/cards-img/Hermione.jpg",
    inMemory: false,
  },
  {
    id: 7,
    name: "Indiana-jones",
    img: "public/cards-img/Indiana-jones.jpg",
    inMemory: false,
  },
  {
    id: 8,
    name: "iron-man",
    img: "public/cards-img/iron-man.jpg",
    inMemory: false,
  },
  {
    id: 9,
    name: "Jack-Skellington",
    img: "public/cards-img/Jack-Skellington.jpg",
    inMemory: false,
  },
  {
    id: 10,
    name: "Jack-Sparrow",
    img: "public/cards-img/Jack-Sparrow.jpg",
    inMemory: false,
  },
  {
    id: 11,
    name: "Jack-Torrance",
    img: "public/cards-img/Jack-Torrance.jpg",
    inMemory: false,
  },
  {
    id: 12,
    name: "Joker",
    img: "public/cards-img/Joker.jpg",
    inMemory: false,
  },
  {
    id: 13,
    name: "mr-incredible-jack",
    img: "public/cards-img/mr-incredible-jack.jpg",
    inMemory: false,
  },
  { id: 14, name: "Nemo", img: "public/cards-img/Nemo.jpg", inMemory: false },
  { id: 15, name: "Neo", img: "public/cards-img/Neo.jpg", inMemory: false },
  { id: 16, name: "Shrek", img: "public/cards-img/Shrek.jpg", inMemory: false },
  { id: 17, name: "Simba", img: "public/cards-img/Simba.jpg", inMemory: false },
  {
    id: 18,
    name: "Terminator",
    img: "public/cards-img/Terminator.jpg",
    inMemory: false,
  },
  {
    id: 19,
    name: "Woody",
    img: "public/cards-img/Woody.jpg",
    inMemory: false,
  },
  { id: 20, name: "Yoda", img: "public/cards-img/Yoda.jpg", inMemory: false },
];
